version: '2'
services:
  python: &python
    image: joanfont/rhodes
    build: .
    links:
      - db
    environment:
      - "DATABASE_DRIVER=postgresql+psycopg2"
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=rhodes"
      - "DATABASE_PASS=rhodes"
      - "DATABASE_NAME=rhodes"
    volumes:
      - ".:/code"
  gunicorn:
    <<: *python
    container_name: gunicorn
    expose:
      - 8080
    ports:
      - "8080:8080"
    command: ["rhodes:app", "-b", "0.0.0.0:8080", "--log-file=-", "--log-level=debug", "--reload"]

  db:
    image: postgres:9.5.3
    container_name: db
    environment:
      - "POSTGRES_USER=rhodes"
      - "POSTGRES_PASSWORD=rhodes"
      - "POSTGRES_DB=rhodes"
    expose:
      - 5432
    volumes:
      - "./opt/postgresql:/var/lib/postgresql/data"

  manage: &manage
    <<: *python
    entrypoint: ["python", "rhodes.py"]

  devel:
    <<: *manage
    ports:
      - "8080:8080"
    command: "runserver"

  alembic: &alembic
    <<: *python
    volumes:
      - "./application/lib/:/code"
      - ".:/app/"
    entrypoint: ["alembic"]

  tests:
    <<: *python
    image: joanfont/rhodes:tests
    build: .
    environment:
      - "GUNICORN_HOST=gunicorn"
      - "GUNICORN_PORT=8080"
    links:
      - gunicorn
    entrypoint: ["nosetests"]
    command: ["api/tests"]

  seed:
    <<: *manage
    command: ["seed", "--sql=config/fixtures.sql"]
