python: &python
  image: joanfont/rhodes
  links:
    - db
  volumes:
    - ".:/code"

gunicorn:
  <<: *python
  ports:
    - "8080:8080"
  command: ["rhodes:app", "-b", "0.0.0.0:8080", "--log-file=-", "--log-level=debug", "--reload"]

db:
  image: postgres:9.5.3
  environment:
    - "POSTGRES_USER=rhodes"
    - "POSTGRES_PASSWORD=rhodes"
    - "POSTGRES_DB=rhodes"
  expose:
    - 5432
  volumes:
    - "/opt/rhodes/postgresql:/var/lib/postgresql/data"

manage: &manage
  <<: *python
  entrypoint: ["python", "rhodes.py"]

devel:
  <<: *manage
  ports:
    - "8080:8080"
  command: "runserver"

alembic: &alembic
  <<: *python
  volumes:
    - "./application/lib/:/code"
    - ".:/app/"
  entrypoint: ["alembic"]

tests:
  <<: *python
  links:
    - gunicorn
  entrypoint: ["nosetests", "api/tests"]

