
MESSAGES_PAGINATION_NEXT = 'next'
MESSAGES_PAGINATION_PREVIOUS = 'previous'

MESSAGES_PAGINATION_CHOICES = [MESSAGES_PAGINATION_NEXT, MESSAGES_PAGINATION_PREVIOUS]

ORDER_ASC = 'asc'
ORDER_DESC = 'desc'
ORDER_CHOICES = [ORDER_ASC, ORDER_DESC]
